In [2]:
import pandas as pd
import re
import nltk
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, accuracy_score
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer
import spacy
from sklearn.svm import SVC
from collections import Counter
from sklearn.metrics import confusion_matrix

In [3]:
df = pd.read_csv("fake_and_real_news.csv")
df

                                                   Text label
0      Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake
1     U.S. conservative leader optimistic of common ...  Real
2     Trump proposes U.S. tax overhaul, stirs concer...  Real
3      Court Forces Ohio To Allow Millions Of Illega...  Fake
4     Democrats say Trump agrees to work on immigrat...  Real
...                                                 ...   ...
9895   Wikileaks Admits To Screwing Up IMMENSELY Wit...  Fake
9896  Trump consults Republican senators on Fed chie...  Real
9897  Trump lawyers say judge lacks jurisdiction for...  Real
9898   WATCH: Right-Wing Pastor Falsely Credits Trum...  Fake
9899   Sean Spicer HILARIOUSLY Branded As Chickensh*...  Fake

[9900 rows x 2 columns]

In [4]:
df.tail(100)

                                                   Text label
9800  Republican Party backs Senate candidate Moore:...  Real
9801  Republican senators want review of 'too big to...  Real
9802   Mexican President Tells Trump One More Time T...  Fake
9803   Black Military Veteran Denied Meal Because Wh...  Fake
9804   WATCH: ‘The View’ Hosts Tell Trump To Get The...  Fake
...                                                 ...   ...
9895   Wikileaks Admits To Screwing Up IMMENSELY Wit...  Fake
9896  Trump consults Republican senators on Fed chie...  Real
9897  Trump lawyers say judge lacks jurisdiction for...  Real
9898   WATCH: Right-Wing Pastor Falsely Credits Trum...  Fake
9899   Sean Spicer HILARIOUSLY Branded As Chickensh*...  Fake

[100 rows x 2 columns]

In [5]:
df.shape

(9900, 2)

In [6]:
# Number of rows labelled as fake news

sum_rows_fake = df[df['label']=='Fake'].shape[0]

print(sum_rows_fake)

5000

In [7]:
sum_rows_real = df[df['label']=='Real'].shape[0]
print(sum_rows_real)

4900

In [8]:
# Missing values count in dataset
missing_values = df["Text"].isnull().sum()
print(str(missing_values) + " missing values")

0 missing values

In [9]:
# number of duplicate values in text column
num_duplicates = df["Text"].duplicated().sum()

print(str(num_duplicates) + " number of duplicate rows")

35 number of duplicate rows

In [10]:
df = df.drop_duplicates(subset="Text", keep="first")
df['Text'] = df['Text'].astype(str)

num_duplicates = df["Text"].duplicated().sum()
print(str(num_duplicates) + " number of duplicate rows")

0 number of duplicate rows

/var/folders/ww/d_0mlqy97tgfbnd0s2t91g_m0000gn/T/ipykernel_48117/1174393082.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Text'] = df['Text'].astype(str)

In [11]:
df['processed_text'] = df['Text'].str.lower()
df['processed_text'] = df['processed_text'].astype(str)

df.head()

/var/folders/ww/d_0mlqy97tgfbnd0s2t91g_m0000gn/T/ipykernel_48117/472969064.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['processed_text'] = df['Text'].str.lower()
/var/folders/ww/d_0mlqy97tgfbnd0s2t91g_m0000gn/T/ipykernel_48117/472969064.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['processed_text'] = df['processed_text'].astype(str)

,Text,label,processed_text
0,Top Trump Surrogate BRUTALLY Stabs Him In The...,Fake,top trump surrogate brutally stabs him in the...
1,U.S. conservative leader optimistic of common ...,Real,u.s. conservative leader optimistic of common ...
2,"Trump proposes U.S. tax overhaul, stirs concer...",Real,"trump proposes u.s. tax overhaul, stirs concer..."
3,Court Forces Ohio To Allow Millions Of Illega...,Fake,court forces ohio to allow millions of illega...
4,Democrats say Trump agrees to work on immigrat...,Real,democrats say trump agrees to work on immigrat...

In [12]:
#preprocessing

# remove punctuation
df['processed_text'] = df['processed_text'].str.replace(r'[^\w\s]', '', regex=True)

#remove special characters
df['processed_text'] = df['processed_text'].str.replace(r'[^A-Za-z0-9 ]+', '', regex=True)

#remove numbers
df['processed_text'] = df['processed_text'].str.replace(r'\d+', '', regex=True)
df.tail()

/var/folders/ww/d_0mlqy97tgfbnd0s2t91g_m0000gn/T/ipykernel_48117/484347262.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['processed_text'] = df['processed_text'].str.replace(r'[^\w\s]', '', regex=True)
/var/folders/ww/d_0mlqy97tgfbnd0s2t91g_m0000gn/T/ipykernel_48117/484347262.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['processed_text'] = df['processed_text'].str.replace(r'[^A-Za-z0-9 ]+', '', regex=True)
/var/folders/ww/d_0mlqy97tgfbnd0s2t91g_m0000gn/T/ipykernel_48117/484347262.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['processed_text'] = df['processed_text'].str.replace(r'\d+', '', regex=True)

,Text,label,processed_text
9895,Wikileaks Admits To Screwing Up IMMENSELY Wit...,Fake,wikileaks admits to screwing up immensely wit...
9896,Trump consults Republican senators on Fed chie...,Real,trump consults republican senators on fed chie...
9897,Trump lawyers say judge lacks jurisdiction for...,Real,trump lawyers say judge lacks jurisdiction for...
9898,WATCH: Right-Wing Pastor Falsely Credits Trum...,Fake,watch rightwing pastor falsely credits trump ...
9899,Sean Spicer HILARIOUSLY Branded As Chickensh*...,Fake,sean spicer hilariously branded as chickensht...

In [13]:
df['processed_text'] = df['processed_text'].astype(str)

df.head(50)

/var/folders/ww/d_0mlqy97tgfbnd0s2t91g_m0000gn/T/ipykernel_48117/612097407.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['processed_text'] = df['processed_text'].astype(str)

,Text,label,processed_text
0,Top Trump Surrogate BRUTALLY Stabs Him In The...,Fake,top trump surrogate brutally stabs him in the...
1,U.S. conservative leader optimistic of common ...,Real,us conservative leader optimistic of common gr...
2,"Trump proposes U.S. tax overhaul, stirs concer...",Real,trump proposes us tax overhaul stirs concerns ...
3,Court Forces Ohio To Allow Millions Of Illega...,Fake,court forces ohio to allow millions of illega...
4,Democrats say Trump agrees to work on immigrat...,Real,democrats say trump agrees to work on immigrat...
5,France says pressure needed to stop North Kore...,Real,france says pressure needed to stop north kore...
6,"Trump on Twitter (August 8): Opioid crisis, No...",Real,trump on twitter august opioid crisis north k...
7,BUSTED: Trump Supporter Used Poll Watcher Cre...,Fake,busted trump supporter used poll watcher cred...
8,Fatal Niger operation sparks calls for public ...,Real,fatal niger operation sparks calls for public ...
9,Trump says he has 'great heart' for immigrant ...,Real,trump says he has great heart for immigrant dr...
10,WATCH: Trump Supporter Tells Muslims That The...,Fake,watch trump supporter tells muslims that they...
11,Corker Has Last Word On Day Care Donnie: ‘On ...,Fake,corker has last word on day care donnie on th...
12,Trump 'dossier' firm: Republicans leaked bank ...,Real,trump dossier firm republicans leaked bank rec...
13,"WATCH: Texas Pastor Angers Parents, Tells Chi...",Fake,watch texas pastor angers parents tells child...
14,Republicans eye alternatives for getting to 20...,Real,republicans eye alternatives for getting to p...
15,REPORT: Sean Spicer Forces Staffers To Surren...,Fake,report sean spicer forces staffers to surrend...
16,Dan Rather Has SHOCKING Response After Trump ...,Fake,dan rather has shocking response after trump ...
17,Senate race in Alabama exposes Republican rift...,Real,senate race in alabama exposes republican rift...
18,WATCH: Kellyanne Conway Says Worldwide Chaos ...,Fake,watch kellyanne conway says worldwide chaos i...
19,"Bond between Trump, Xi in meetings played role...",Real,bond between trump xi in meetings played role ...
20,"Trump Gets Tired Of ‘Hamilton’ Feud, Reignite...",Fake,trump gets tired of hamilton feud reignites a...
21,"A Trump Fan Picks A Fight On A Plane, So The ...",Fake,a trump fan picks a fight on a plane so the c...
22,Russia probe should focus on Trump financial t...,Real,russia probe should focus on trump financial t...
23,Former Trump campaign adviser Page to testify ...,Real,former trump campaign adviser page to testify ...
24,State Department presses North Korea to releas...,Real,state department presses north korea to releas...
25,Trump’s Latest Tweet Has A GLARING Mistake Th...,Fake,trumps latest tweet has a glaring mistake tha...
26,"Trump Falls Flat On His Face In Israel, Doesn...",Fake,trump falls flat on his face in israel doesnt...
27,Trump says healthcare reform push may need add...,Real,trump says healthcare reform push may need add...
28,Wilbur Ross seen imposing Mexico sugar deal ov...,Real,wilbur ross seen imposing mexico sugar deal ov...
29,State funding changes in spotlight in Republic...,Real,state funding changes in spotlight in republic...
30,FBI chief promises to disclose any attempt to ...,Real,fbi chief promises to disclose any attempt to ...
31,"Democrats dig in, delay against Dodd-Frank ove...",Real,democrats dig in delay against doddfrank overh...
32,"Someone Snapped The BEST Photo Of Trump Ever,...",Fake,someone snapped the best photo of trump ever ...
33,Comey's friend says he's turning over Comey's ...,Real,comeys friend says hes turning over comeys tru...
34,Obama Pens STUNNING Response To Trump’s Cold-...,Fake,obama pens stunning response to trumps coldbl...
35,White House says will work with Rubio on child...,Real,white house says will work with rubio on child...
36,Republican tax bill retains U.S. electric vehi...,Real,republican tax bill retains us electric vehicl...
37,Factbox: Trump on Twitter (Aug 24) - Debt ceil...,Real,factbox trump on twitter aug debt ceiling fa...
38,Lawsuit against Trump over foreign payments ex...,Real,lawsuit against trump over foreign payments ex...
39,Twitter Has Absolute Field Day Laughing At Tr...,Fake,twitter has absolute field day laughing at tr...
40,WATCH: Don Lemon CRUSHES Trump Supporter For ...,Fake,watch don lemon crushes trump supporter for c...
41,"U.S. corporate tax cut goal in doubt, Trump di...",Real,us corporate tax cut goal in doubt trump dines...
42,Federal Judge Tells Anti-Vaxxers To Go F*ck T...,Fake,federal judge tells antivaxxers to go fck the...
43,Trump asks for probe into imports of foreign-m...,Real,trump asks for probe into imports of foreignma...
44,The Internet Drags Trump’s Son For Saying ‘Th...,Fake,the internet drags trumps son for saying ther...
45,REPORT: Team Trump Tried To Bribe Networks Fo...,Fake,report team trump tried to bribe networks for...
46,Republican strategy on healthcare bill in flux...,Real,republican strategy on healthcare bill in flux...
47,"China's Xi, Trump discuss 'global hot-spot iss...",Real,chinas xi trump discuss global hotspot issues ...
48,Trump has talked to top lawmakers about immigr...,Real,trump has talked to top lawmakers about immigr...
49,U.S. officials will not label treatment of Roh...,Real,us officials will not label treatment of rohin...

In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

texts = df['processed_text'].tolist()

embeddings = model.encode(texts, show_progress_bar=True)

Batches:   0%|          | 0/309 [00:00<?, ?it/s]

In [ ]:
import numpy as np

embedding_df = pd.DataFrame(embeddings, columns=[f'embedding_{i}' for i in range(embeddings.shape[1])])

df = df.reset_index(drop=True)
embedding_df = embedding_df.reset_index(drop=True)
df = pd.concat([df, embedding_df], axis=1)

df.head()

,Text,label,processed_text,embedding_0,embedding_1,embedding_2,embedding_3,embedding_4,embedding_5,embedding_6,...,embedding_374,embedding_375,embedding_376,embedding_377,embedding_378,embedding_379,embedding_380,embedding_381,embedding_382,embedding_383
0,Top Trump Surrogate BRUTALLY Stabs Him In The...,Fake,top trump surrogate brutally stabs him in the...,0.038263,-0.084156,0.031022,-0.054934,0.037044,0.003077,0.011666,...,0.023001,0.034201,0.017600,0.034051,-0.028088,0.021096,0.011347,-0.044088,0.032909,0.065789
1,U.S. conservative leader optimistic of common ...,Real,us conservative leader optimistic of common gr...,0.014601,-0.007420,0.027064,-0.013856,0.005874,-0.003401,0.024745,...,0.025185,0.036019,-0.005060,-0.064645,0.030221,-0.042490,0.013098,-0.070048,0.017617,0.061255
2,"Trump proposes U.S. tax overhaul, stirs concer...",Real,trump proposes us tax overhaul stirs concerns ...,-0.062292,-0.014460,0.063104,-0.034399,-0.013986,0.007709,0.022859,...,0.017728,-0.046493,-0.075460,0.015458,-0.076326,-0.079142,0.080881,-0.094814,0.029084,0.022779
3,Court Forces Ohio To Allow Millions Of Illega...,Fake,court forces ohio to allow millions of illega...,-0.083253,-0.000753,0.003586,-0.013900,-0.050391,-0.021573,0.043673,...,0.075613,-0.046366,0.043325,-0.048957,0.014632,0.011940,0.009021,0.057602,0.003887,0.013239
4,Democrats say Trump agrees to work on immigrat...,Real,democrats say trump agrees to work on immigrat...,-0.021289,0.051865,0.004178,0.027849,0.048122,-0.024927,-0.037811,...,0.036563,-0.037612,-0.007526,-0.082493,0.077802,-0.042493,0.034226,-0.003799,0.056570,0.031056

In [27]:

from sklearn.neural_network import MLPClassifier

X = df[[col for col in df.columns if col.startswith('embedding_')]]
y = df['label'].replace({'real': 0, 'fake': 1})

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [28]:
mlp = MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=20, random_state=42)
mlp.fit(X_train, y_train)
y_pred = mlp.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, y_pred):.3f}")

Accuracy: 0.962

/opt/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(

In [29]:
from sklearn.metrics import classification_report, confusion_matrix

print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

        Fake       0.95      0.98      0.96       977
        Real       0.98      0.95      0.96       996

    accuracy                           0.96      1973
   macro avg       0.96      0.96      0.96      1973
weighted avg       0.96      0.96      0.96      1973

Confusion Matrix:
 [[953  24]
 [ 50 946]]

In [ ]:
import re
import pandas as pd

def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)        
    text = re.sub(r'[^A-Za-z0-9 ]+', '', text) 
    text = re.sub(r'\d+', '', text)            
    return text

new_text = """

"""

processed = preprocess_text(new_text)

text_embedding = model.encode([processed])  

text_embedding_df = pd.DataFrame(
    text_embedding,
    columns=[f'embedding_{i}' for i in range(text_embedding.shape[1])]
)

pred = mlp.predict(text_embedding_df)  

print(pred)

['Fake']